
/**
* calcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Sunday, 8 May, 2022 4:19:52 PM IST
*/

public interface calcOperations 
{
  double addfn (double a, double b);
  double subfn (double a, double b);
  double mulfn (double a, double b);
  double divfn (double a, double b);
} // interface calcOperations
