
/**
* calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Sunday, 8 May, 2022 4:19:52 PM IST
*/

public interface calc extends calcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calc
